GestionAutorizacionesSaludWeb/src/main/java/com/sos/gestionautorizacionessaludweb/util/MenuBean.java
package com.sos.gestionautorizacionessaludweb.util;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;

import org.apache.log4j.Logger;

import co.com.sos.logic.vo.PrestadorVO;
import co.com.sos.logic.vo.UsuarioVO;
import co.com.sos.logic.voa.UsuarioVOA;

import com.sos.excepciones.LogicException;
import com.sos.gestionautorizacionessaluddata.model.ModuloVO;
import com.sos.gestionautorizacionessaluddata.model.ServicioVO;
import com.sos.gestionautorizacionessaludejb.controller.MenuController;
import com.sos.gestionautorizacionessaludejb.util.Messages;
import com.sos.util.jsf.FacesUtil;
import com.sos.gestionautorizacionessaludweb.util.UsuarioBean;

/**
 * Class MenuBean
 * 
 * @author Jerson Viveros
 * @version 1.0
 */
public class MenuBean implements Serializable{
	private static final long serialVersionUID = -3604978039031547472L;
	
	private static final Logger LOGGER = Logger.getLogger(UsuarioBean.class);

	/**
	 * La lista de procesos se usa para pintar todos los procesos a los que
	 * tiene acceso el usuario
	 */
	private List<ModuloVO> modulos;

	/** Opcion seleccionada por el usuario */
	private String opcion;
	
	private boolean usuarioIps;
	
	private PrestadorVO prestadorVO;

	/**
	 * Inicia el menu dinamico, consulta en base de datos las tablas
	 * TbModulos y tbServicios
	 */
	@PostConstruct
	public void init() {
		boolean coordinadorASI = false;
		MenuController mcmc = new MenuController();
		try {
			String usr = ((UsuarioBean) FacesUtil.getBean(ConstantesWeb.USUARIO_BEAN)).getNombreUsuario();
			setModulos(mcmc.getModulos(usr));
			for (ModuloVO moduloVO : modulos) {
				if (ConstantesWeb.PERFIL_COORDINADORA == moduloVO.getConsecutivoCodigoPerfil()){
					coordinadorASI = true;
				}
				for (ServicioVO servicioVO : moduloVO.getServicios()) {				
					servicioVO.setDeshabilitado(opcionInactiva(servicioVO.getAction().trim()));
				}
			}
			UsuarioVO usuarioConsultaVO = new UsuarioVO();
			usuarioConsultaVO.setLogin(FacesUtils.getUserName());

			UsuarioVOA usuarioVoa = new UsuarioVOA();
			UsuarioVO usuarioResultadoVO = usuarioVoa. consultarUsuario(usuarioConsultaVO);
				
			prestadorVO = usuarioResultadoVO.getPrestadorAsociado();
			
			usuarioIps = prestadorVO.getCodInternoPrestador()==null?false:true;
			
			FacesUtils.setSessionParameter(ConstantesWeb.ES_USUARIOS_IPS, usuarioIps);
			FacesUtils.setSessionParameter(ConstantesWeb.ES_COORDINADOR_ASI, coordinadorASI);

		} catch (LogicException e) {
			LOGGER.error(e.getMessage(), e);
			mostrarMensajes(e.getMessage(), "blue");
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), e);
			mostrarMensajes(Messages.getValorExcepcion(ConstantesWeb.ERROR_EXCEPCION_INESPERADA), ConstantesWeb.COLOR_ROJO);
		}
	}
	
	
	private boolean opcionInactiva(String opcion) {
		return ConstantesWeb.OPCION_INGRESAR_SOLICITUD.equals(opcion) 
				|| ConstantesWeb.OPCION_PROGRAMACION_ENTREGA.equals(opcion)
				|| ConstantesWeb.OPCION_CAMBIAR_DIRECCIONAMIENTO.equals(opcion)
				|| ConstantesWeb.OPCION_CAMBIAR_FECHA_ENTREGA.equals(opcion);
	}

	/**
	 * Permite realizar la navegacion del menu dinamico
	 * 
	 * @return regla de navegacion
	 */
	public String navegar() {
		return getOpcion();
	}

	/**
	 * Metodo encargado de mostrar los mensajes.
	 *
	 * @param mensaje
	 *            the mensaje
	 * @param color
	 *            the color
	 */
	private void mostrarMensajes(String mensaje, String color) {
		MessagesPopupBean messagesPopupBean = (MessagesPopupBean) FacesUtils.getManagedBean(ConstantesWeb.MESSAGES_POPUP_BEAN);
		messagesPopupBean.setColor(color);
		messagesPopupBean.showError(mensaje);
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	public String getOpcion() {
		return opcion;
	}

	public void setModulos(List<ModuloVO> modulos) {
		this.modulos = modulos;
	}

	public List<ModuloVO> getModulos() {
		return modulos;
	}

	public boolean isUsuarioIps() {
		return usuarioIps;
	}

	public void setUsuarioIps(boolean usuarioIps) {
		this.usuarioIps = usuarioIps;
	}

	public PrestadorVO getPrestadorVO() {
		return prestadorVO;
	}

	public void setPrestadorVO(PrestadorVO prestadorVO) {
		this.prestadorVO = prestadorVO;
	}

}

GestionAutorizacionesSaludWeb/src/main/java/com/sos/gestionautorizacionessaludweb/util/MessagesPopupBean.java
/*
 * @author Jorge Andres Garcia Erazo - Geniar S.A.S
 * @since 04/09/2013
 * @version 1.0
 */
package com.sos.gestionautorizacionessaludweb.util;

import java.io.Serializable;
import java.util.List;

import javax.faces.event.ActionEvent;



/**
 * Class MessagesPopupBean.
 *
 * @author sisddc01
 * @version 4/09/2012
 */
public class MessagesPopupBean implements Serializable {

	/** Constante serialVersionUID. */
	private static final long serialVersionUID = 3463993965199399525L;

	/** show. */
	private boolean show;

	/** title. */
	private String title;

	/** msgs. */
	private String[] msgs;

	/** info. */
	private boolean info;

	/** url. */
	private String url;
	
	/** The color. */
	private String color = "blue";
	
	/** show. */
	private boolean botonAceptar;

	/**
	 * Instancia nueva de messages popup bean.
	 */
	public MessagesPopupBean() {
		//Metodo en blanco
	}

	/**
	 * Show info.
	 *
	 * @param msgs the msgs
	 */
	public void showInfo(String msgs) {
		this.msgs = new String[] { msgs };
		info = true;
		show = true;
	}

	/**
	 * Show info.
	 *
	 * @param msgs the msgs
	 * @param url the url
	 */
	public void showInfo(String msgs, String url) {
		this.msgs = new String[] { msgs };
		info = true;
		show = true;
		this.url = url;
	}

	/**
	 * Show info.
	 *
	 * @param msgs the msgs
	 */
	public void showInfo(String[] msgs) {
		this.msgs = msgs;
		info = true;
		show = true;
	}

	/**
	 * Show info.
	 *
	 * @param msgs the msgs
	 */
	public void showInfo(List<String> msgs) {
		this.msgs = new String[msgs.size()];
		for (int i = 0; i < msgs.size(); i++) {
			this.msgs[i] = msgs.get(i);
		}
		info = true;
		show = true;
	}

	/**
	 * Show error.
	 *
	 * @param msgs the msgs
	 */
	public void showError(String msgs) {
		this.msgs = new String[] { msgs };
		info = false;
		show = true;
	}

	/**
	 * Show error.
	 *
	 * @param msgs the msgs
	 */
	public void showError(String[] msgs) {
		this.msgs = msgs;
		info = false;
		show = true;
	}

	/**
	 * Show error.
	 *
	 * @param msgs the msgs
	 */
	public void showError(List<String> msgs) {
		this.msgs = new String[msgs.size()];
		for (int i = 0; i < msgs.size(); i++) {
			this.msgs[i] = msgs.get(i);
		}
		info = false;
		show = true;
	}

	/**
	 * Close.
	 *
	 * @param event the event
	 */
	public void close(ActionEvent event) {
		msgs = null;
		title = "";
		info = false;
		show = false;
		((Confirmacion) FacesUtils.getManagedBean(ConstantesWeb.CONFIRMACION_BEAN))
				.close(null);

	}

	/**
	 * Close.
	 *
	 * @return string
	 */
	public String close() {
		msgs = null;
		title = "";
		info = false;
		show = false;
		((Confirmacion) FacesUtils.getManagedBean(ConstantesWeb.CONFIRMACION_BEAN))
				.close(null);
		return url;
	}

	/**
	 * Comprueba si es show.
	 *
	 * @return true, si es show
	 */
	public boolean isShow() {
		return show;
	}

	/**
	 * Establece show.
	 *
	 * @param show Nuevo show
	 */
	public void setShow(boolean show) {
		this.show = show;
	}

	/**
	 * Obtiene title.
	 *
	 * @return title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Establece title.
	 *
	 * @param title Nuevo title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Obtiene msgs.
	 *
	 * @return msgs
	 */
	public String[] getMsgs() {
		return msgs;
	}

	/**
	 * Establece msgs.
	 *
	 * @param msgs Nuevo msgs
	 */
	public void setMsgs(String[] msgs) {
		this.msgs = msgs;
	}

	/**
	 * Comprueba si es info.
	 *
	 * @return true, si es info
	 */
	public boolean isInfo() {
		return info;
	}

	/**
	 * Establece info.
	 *
	 * @param info Nuevo info
	 */
	public void setInfo(boolean info) {
		this.info = info;
	}

	/**
	 * Obtiene url.
	 *
	 * @return url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Establece url.
	 *
	 * @param url Nuevo url
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Gets the color.
	 *
	 * @return the color
	 */
	public String getColor() {
		return color;
	}

	/**
	 * Sets the color.
	 *
	 * @param color the color to set
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * @return the botonAceptar
	 */
	public boolean isBotonAceptar() {
		return botonAceptar;
	}

	/**
	 * @param botonAceptar the botonAceptar to set
	 */
	public void setBotonAceptar(boolean botonAceptar) {
		this.botonAceptar = botonAceptar;
	}
	
	
}

GestionAutorizacionesSaludWeb/src/main/java/com/sos/gestionautorizacionessaludweb/util/VersionAppBean.java
package com.sos.gestionautorizacionessaludweb.util;


import java.io.Serializable;
import java.net.InetAddress;


/**
 * The Class VersionAppBean.
 * 
 * @author hcuenca
 * @version 28/11/2014
 * @type: Clase
 * @name: VersionAppBean
 * @description: Clase encargada de ser la controladora de aspectos relacionados
 *               con la version dela aplicacion
 */
public class VersionAppBean implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7316100275043010544L;

	/**
	 * The version app.
	 * 
	 * @author hcuenca
	 * @version 28/11/2014
	 * @type: Atributo
	 * @name: versionApp
	 * @description: Variable de clase encargada de capturar y almacenar el
	 *               valor de la version de la App
	 */
	private String versionApp;


	/**
	 * Instantiates a new version app bean.
	 * 
	 * @author hcuenca
	 * @version 11/10/2014
	 * @type: Constructor
	 * @name: GenerarFormatosComunicadosBean
	 * @description: Constructor por defecto, de la clase
	 *               GenerarFormatosComunicadosBean
	 */
	public VersionAppBean() {

	}

	/**
	 * Gets the version app.
	 * 
	 * @author hcuenca
	 * @version 28/11/2014
	 * @return String: Retorna el valor del atributo de clase: versionApp
	 * @type: Comportamiento
	 * @name: getVersionApp
	 * @description: Metodo get del atributo de clase: versionApp
	 */
	public String getVersionApp() {
		versionApp = ConstantesWeb.VERSION + "-"+ getHostName();		
		return versionApp;
	}

	/**
	 * Sets the version app.
	 * 
	 * @author hcuenca
	 * @version 28/11/2014
	 * @param versionApp
	 *            the new version app
	 * @type: Comportamiento
	 * @name: setVersionApp
	 * @description: Metodo set del atributo de clase: versionApp
	 */
	public void setVersionApp(String versionApp) {
		this.versionApp = versionApp;
	}

	
	
	public String getHostName() {
		String host="";
		try{
			host = InetAddress.getLocalHost().getHostName();
		} catch (final Exception e) { /* no-op */
			host = "Not Found";
		}
		return host;
	}
}

GestionAutorizacionesSaludWeb/src/main/webapp/templates/cabecera.xhtml
<div xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j">

    
	 <a4j:form>
		<div class="header"	style="vertical-align: top; width: 100%; text-align: right; color: white; font-size: 10pt; margin-top: 10" id="cabecera">
			
			<div align="right">
				<h:panelGrid columns="3">
					<h:panelGroup>
						<h:outputText value="#{usuarioBean.userName} |"
							style="color: white;" />
						<h:commandLink style="color: white;" value="Cerrar Sesion"
							action="#{usuarioBean.logout}" />
					</h:panelGroup>
				</h:panelGrid>
			</div>
			<div align="right" style="font-size: 7pt;" >
				<h:outputText value="Servidor: #{versionAppBB.hostName}" style="color: white;" />
			</div>
			
			<h1 align="center" style="margin-right: 35%">
				<ui:insert name="pageName" />
			</h1>
		</div>		
	</a4j:form>

</div>

GestionAutorizacionesSaludWeb/src/main/webapp/templates/cabeceraBPM.xhtml
<div xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j">
    
	 <a4j:form>
	   
		<div class="header"	style="vertical-align: top; width: 100%; text-align: right; color: white; font-size: 10pt; margin-top: 10">			
			<h1 align="center" style="margin-right: 35%">
				<ui:insert name="pageName" />
			</h1>
		</div>	
		 <div align="right" style="font-size: 7pt;" >
			<h:outputText value="Servidor: #{versionAppBB.hostName}" style="color: white;" />
		</div>	
	</a4j:form>

</div>

GestionAutorizacionesSaludWeb/src/main/webapp/templates/inicioBpm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:c="http://java.sun.com/jstl/core">
<f:loadBundle var="label" basename="properties.etiquetas" />

<head>
<script type="text/javascript">
function validateAlphaNumeric(evt) {
  var theEvent = evt || window.event;
  var key = theEvent.keyCode || theEvent.which;
  key = String.fromCharCode( key );
  var regex = /^[0-9a-zA-Z]+$/;
  if( !regex.test(key) ) {
    theEvent.returnValue = false;
    if(theEvent.preventDefault) theEvent.preventDefault();
  }
}
function validateDecimalNumericSlash(evt) {
  var theEvent = evt || window.event;
  var key = theEvent.keyCode || theEvent.which;
  key = String.fromCharCode( key );
  var regex = /[0-9/]|\./;
  if( !regex.test(key) ) {
    theEvent.returnValue = false;
    if(theEvent.preventDefault) theEvent.preventDefault();
  }
}
function validateDecimalNumeric(evt) {
  var theEvent = evt || window.event;
  var key = theEvent.keyCode || theEvent.which;
  key = String.fromCharCode( key );
  var regex = /[0-9]|\./;
  if( !regex.test(key) ) {
    theEvent.returnValue = false;
    if(theEvent.preventDefault) theEvent.preventDefault();
  }
}
function validateNumeric(evt) {
  var theEvent = evt || window.event;
  var key = theEvent.keyCode || theEvent.which;
  if ( isNaN( String.fromCharCode(evt.keyCode) )){
  	theEvent.returnValue = false;
    if(theEvent.preventDefault) theEvent.preventDefault();
  }
}
</script>
<script type="text/javascript">        
        function disablementFunctionFechaConsulta(day){
	        var curDt = new Date();
	        var minDt = new Date();
        	var re;
        	var diasMenos = ${minimaFechaConsulta};
        	minDt = new Date();
        	minDt.setTime( minDt.getTime() - (diasMenos * 86400000));
            if (curDt==undefined){
                curDt = day.date.getDate;
            }
            if (curDt.getTime() - day.date.getTime() &gt;0) re= true; else return false; 
            if (minDt.getTime() - day.date.getTime() &lt;0) re= true; else re= false;  
            return re;
        }
    </script>
<script type="text/javascript">
       function disablementFunctionFechaSolicitud(day){
       		var curDt = new Date();
        	var minDt = new Date();
        	var re;
        	var diasMenos = ${minimaFechaSolicitud};
        	minDt = new Date();
        	minDt.setTime( minDt.getTime() - (diasMenos * 86400000));
            if (curDt==undefined){
                curDt = day.date.getDate;
            }
            if (curDt.getTime() - day.date.getTime() &gt;0) re= true; else return false; 
            if (minDt.getTime() - day.date.getTime() &lt;0) re= true; else re= false;  
            return re;
        }
    </script>
<script type="text/javascript">
       function disablementFunctionFecha(day){
        	var re;
        	var curDt = new Date();
            if (curDt==undefined){
                curDt = day.date.getDate;
            }
            if (curDt.getTime() - day.date.getTime() &gt;0) return true; else return false; 
        }
    </script>
<!-- page title param passed in by param -->
<title><h:outputText value="#{label['titulo.pagina']}" />
	#{pageTitle}</title>
<meta http-equiv="keywords" content="enter,your,keywords,here" />
<meta http-equiv="description"
	content="A short description of this page." />
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

<link rel="stylesheet" type="text/css"
	href="${request.contextPath}/css/estilo_sos-v2.css" />
<link rel="stylesheet" type="text/css"
	href="${request.contextPath}/css/estilosNuevos.css" />
<link rel="stylesheet" type="text/css"
	href="${request.contextPath}/css/sos-richfaces-3.1.5.css" />
<link rel="stylesheet" type="text/css"
	href="${request.contextPath}/css/sos.css" />
<script type="text/javascript" src="${request.contextPath}/resources/js/validaciones.js"></script>
</head>
<body>

	<div class="page">
		<ui:include src="./cabeceraBPM.xhtml" />

		<h:panelGrid id="grid" columns="2">

			
			<rich:column
				style="text-align: center; width: 80%; border: none; vertical-align: top;">
				<div class="content">
					<ui:insert name="content" />
				</div>
			</rich:column>
		</h:panelGrid>
		<div class="footer">
			<ui:include src="./messagesPopup.xhtml" />
			<ui:include src="./messagesFacesPopup.xhtml" />
			<ui:include src="./ventanaProcesando.xhtml" />
			<a4j:status id="ajaxStatus"
				onstart="#{rich:component('waitPanel')}.show('',{top:'200px', left:'560px',height:'100px', width:'120px'})"
				onstop="#{rich:component('waitPanel')}.hide()" />
		</div>
	</div>

</body>
</html>

GestionAutorizacionesSaludWeb/src/main/webapp/templates/messagesFacesPopup.xhtml
<h:form id="formPopupFacesMessages" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<rich:modalPanel id="modalFacesError" autosized="true" width="450"
		showWhenRendered="#{facesContext.maximumSeverity != null}">
		<div class="box-cont-ppal-home" align="center">
			<f:facet name="header">
				<f:facet name="header">
					<h:panelGroup>
						<h:outputText value="Mensaje" />
					</h:panelGroup>
				</f:facet>
			</f:facet>
			<h:panelGrid columns="0" width="100%" style="align: center;"
				styleClass="box-mrgBottom" border="0">
				<h:panelGroup>
					<div align="left">
						<rich:messages layout="list" errorLabelClass="mensajeAdvertencia"
							fatalLabelClass="mensajeAdvertencia"
							infoLabelClass="mensajeInformativo"
							warnLabelClass="mensajeAdvertencia">
							<f:facet name="errorMarker">
								<h:graphicImage value="/css/images/ico/anular.gif" />
							</f:facet>
						</rich:messages>
					</div>
					<p />
					<div align="center">
						<a4j:commandButton style="text-align: center;" value="Aceptar"
							styleClass="aceptar"
							onclick="Richfaces.hideModalPanel('modalFacesError');">
						</a4j:commandButton>
					</div>
				</h:panelGroup>
			</h:panelGrid>
		</div>
	</rich:modalPanel>
</h:form>

GestionAutorizacionesSaludWeb/src/main/webapp/templates/messagesPopup.xhtml
<h:form id="formPopupMessages" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<rich:modalPanel id="modalPnlPop" autosized="true" width="250"
		showWhenRendered="#{messagesPopupBean.show}">
		<f:facet name="header">
			<h:panelGroup>
				<h:outputText
					value="#{(messagesPopupBean.info)?(label['messagesExceptionPopup.label.titleInfo']):(label['messagesExceptionPopup.label.title'])}" />
			</h:panelGroup>
		</f:facet>
		<f:facet name="controls">
			<a4j:outputPanel rendered="#{messagesPopupBean.info}">
				
			</a4j:outputPanel>
			<a4j:outputPanel rendered="#{!messagesPopupBean.info}">
				
			</a4j:outputPanel>
		</f:facet>
		<h:panelGrid columns="0" width="100%" style="align: center;"
			border="0">
			<h:panelGroup>
				<ui:repeat var="msg" value="#{messagesPopupBean.msgs}">
					<div align="left">
						<h:outputText value="#{msg}"
							style="color: #{messagesPopupBean.color};"
							rendered="#{!messagesPopupBean.info}" />
						<h:outputText value="#{msg}"
							style="color: #{messagesPopupBean.color};"
							rendered="#{messagesPopupBean.info}" />
					</div>
					<br />	
					<div align="center">
						<a4j:commandButton	id="modalPnlCloseButton1"
											actionListener="#{messagesPopupBean.close}"
											style="text-align: center;" 
											value="Aceptar"
											styleClass="aceptar"
											onclick="Richfaces.hideModalPanel('modalPnlPop');">
						</a4j:commandButton>
					</div>					
				</ui:repeat>
			</h:panelGroup>
		</h:panelGrid>
	</rich:modalPanel>
</h:form>

GestionAutorizacionesSaludWeb/src/main/webapp/templates/ventanaProcesando.xhtml
<rich:modalPanel id="waitPanel" style="text-align:center"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:panelGrid columns="1" id="ajaxLoadingM"
		style="text-align: center; background-color: transparent; width: 100%;">
		<h:graphicImage id="imgLoadin" url="/imagenes/connect_active.gif"></h:graphicImage>
		<h:outputText id="txtProcesand" style="font-size: 7pt"
			value="Procesando..." />
	</h:panelGrid>
</rich:modalPanel>